### ISSUE TITLE
Yo iron, what's up man?

### ISSUE THREAD

**Issue by IroncladDev** [Iron-Programming/hello-world#2]
I haven't really found a way to communicate with ya besides github so yeah thought I'd talk to ya here.

**Comment by nacochran** [comment]
Hey Leviathan! I've been really busy, but I'm learning a lot of cool stuff computer-wise right now. I'm learning C++ and other IT-related things right now. I've learned a lot more about the anatomy of computers recently, it's been pretty fun. 

I was talking to Phantom Falcon some about Digital Audio Workstations (DAWs) recently - I have been learning some about the Adobe programs. I just used Adobe AfterEffects and Adobe Primiere to make my first Youtube video, and I'm learning about Adobe Photoshop right now. If my project with @PF goes though then I'll probably use Adobe Audition.

What about you?

**Comment by IroncladDev** [comment]
I've been learning about computer hardware lately and hopefully will start learning about Cybersecurity, Cloud Storage, and Ethical Hacking.  I've still been doing a lot of fullstack dev and learning how to make discord bots.

I remade my website and am trying to get a job as a freelancer or for a company.  I'm working towards that rn.
In january I'll be going to do an online university, so I won't have enough time to code as much.

So actually, my KA account got banned and I guess for a good reason.  It's a waste of time on there if you know what I mean.  I am not associating with KA anymore.

Since you don't use discord, do you use https://gitter.im ?

**Comment by nacochran** [comment]
Sounds good! I am actually taking online college classes myself as well, which is where I am learning C++ and working towards my degree in IT. I've learned some about Cybersecurity over the years, and I am interested in studying it in more depth later.  I will also be learning Python later this year. 

Ah, too bad. I still use KA though. Although I haven't been coding much on it I use it for learning various topics (recently I've been going through their government courses). 

I am only allowed to use certain communication programs. The main platforms I communicate with others on are Duolingo (for studying languages), KA, and Github. I am starting to use other websites as well though.

**Comment by IroncladDev** [comment]
I guess we can use github to communicate, but gitter, actually, is meant to be _for_ github users and is kind of a part of it but not completely.

I originally would have used Duo but the problem is, that they are really liberal.  I mean in the ways where they are teaching homosexuality to people that learn from the site.  I have found some content on there was wasn't really clean in terms of that so I stopped using it.

Maybe I could make a communication app on github between us so we can communicate a bit better, maybe with firebase.  That's something I still gotta learn.

**Comment by nacochran** [comment]
Oh yes, I remember gitter now. I might use that in the future if I start using Github more often for programming.

You're right, and that makes me sad. The first couple of years I used it I didn't really come across much of it but this last year I've seen several of their stories with bad themes. Most of the actual "learning" content doesn't go into any of that though, at least in my experience. I still use Duolingo for now, but sometime I might transition to Babel or another language-learning app.

I think Github is fine. 

One quick question, have you ever taken apart computers or done any such work? I just started doing some of that, and it is pretty fun.

**Comment by IroncladDev** [comment]
Sorry for the late response.  I didn't really get an email about this.

Me and my family use Rosetta Stone.  It costs money but gets the job done.

I did take apart many computers when I was younger.  It's fun to just kind of collect parts from them like RAM sticks, CPUs, etc.

**Comment by nacochran** [comment]
Ah, yes. I have heard about Rosetta Stone. I recently took a linguistics course and in that time I studied the most efficient way to learn a language. As I have found in my research the best way to learn a language is not to even use a language learning app, although those are great for starting out. My strategy is to start with apps and usually resources like a youtube channel, and then transition to real-life content. I read, watch, and listen to media in that language (books/websites, youtube videos, and podcasts) as much as I can. For example, I know that KA and BrainPOP both offer content in Espanol so I have been starting to use those versions of their sites.

I also recently found out about Creation.com's Spanish articles so I am going to look into those as well.

So I consider myself in "phase 2" of learning Spanish, which is where I don't really "study" Spanish anymore (just for the sake of studying), and I started learning French recently so I am in phase 1 for that. I actually plan to learn a lot of languages--after taking that linguistics course I got pretty interested in languages, including sign languages which I might learn as well.

It is fun to do that. :-)

Speaking of which, if you know enough Spanish then I'd love to have conversations with you in Spanish because the biggest tip I found in learning languages was to talk in them. Real-life talking is best of course, but online lets you look up words you don't know to help improve your vocabulary on the spot.

Hablaré contigo más tarde!

**Comment by IroncladDev** [comment]
I do know enough spanish to be able to get by I guess so we can talk in spanish to each other.

My mom always wants me to talk to people in spanish but usually I don't get the chance.

I guess it will be a lot easier to do that in Gitter if you don't mind but if you can't use it for some reason, nos pero continuar usar el github.

**Comment by nacochran** [comment]
Bueno! Desafortunadamente (esa palabra es ridícula), yo no puedo usar el Gitter, lo siento.

Sobre la ultima oracion, no debería ser "Nosotras podemos continuar usando el github"? Porque la palabra "nos" es un objeto sustantivo y no es un sujeto.

¿Alguin mas en tu familia habla español? ¿O otras idiomas?

Este será mucho divertido, créeme.

Tambien, no es un problema si tienes que usar el traductor de google para unas palabras, porque así es como aumento mi vocabulario.

Symbols (for reference): Á, á, É, é, Í, í, Ó, ó, Ú, ú, Ü, ü, Ñ, ñ, ¿, ¡

**Comment by IroncladDev** [comment]
En realidad es "Nosotros", no es "Nosotras".
Tu hablos mucho español.  Yo hablo un poco.  No se mucho.

el Google Translate es muy útil.

Mi família hablo un poco pero mi padre hablo español fluente
Nosotros hablo en ingles generalmente

**Comment by nacochran** [comment]
Sí, sí, tu estas correcta, deberías "nosotros" no "nosotras," mi mal. 

Estas bien. A veces yo uso el traductor de google tambien. ¿Que materiales usas para apprender español además el Rosetta Stone? Mi primo lo compró un biblia española, y planeo hacerlo también. También uso un himnario español.

También busco buenos canales de youtube en español para ver. Pronto planeo comprar un diccionario de español y empezar a pedir prestados libros en español de mi biblioteca. 

Unas de mi familia y amigos esta appriendo espanol tambien. 

Puedo escribir, leer y hablar espanol de manera decente, pero todavia me cuesta mucho entender el espanol hablado.

Tambien, soy demasiado perezoso para escribir todos los acentos en español.

**Comment by IroncladDev** [comment]
Yo uso el rosetta stone solamente.  No soy desesperda al apprender español.

Yo puedo comprender español cuando una persona esta hablar conmigo pero es mas dificil que leer español y comprender.

Yo tambien puedo escribir en español y hablo un poco.

Es bueno hablar con el programador de hierro

**Comment by nacochran** [comment]
Bueno! Hablara contigo mas tiempo!

**Comment by IroncladDev** [comment]
👍

**Comment by IroncladDev** [comment]
Hey Iron, want to do this competition?
I'm going to do it when it starts.
https://replit.com/site/kajam

All you need is an account on https://replit.com
It's for coding mainly but you can code in _any_ language.

**Comment by nacochran** [comment]
Ah, man. That looks really cool..... you might have convinced me. I will try to think of an addicting app-like game because I don't have enough time for an epic cool game.

**Comment by IroncladDev** [comment]
I'm going to use webgl and make a first person shooter.

All it takes is to create an account in replit and you can do it.

**Comment by nacochran** [comment]
Sounds cool. I'm glad you showed me replit, although I probably won't be able to compete this time.

**Comment by IroncladDev** [comment]
Oh okay.
